name: Build Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gperf ccache dfu-util

      - name: Set up Python environment
        run: |
          python3 -m venv zmk-env
          source zmk-env/bin/activate
          pip install west

      - name: Initialize and update West
        run: |
          west init -l app/
          west update
          west zephyr-export

      - name: Build firmware
        run: |
          source zmk-env/bin/activate
          west build -s app -b nice_nano_v2 -- -DZMK_CONFIG="$(pwd)/config"

      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
